;****p* ksi/hello
;  NAME
;    hello -- print 'Hello, World!', and exit
;  DESCRIPTION
;    Prints the message 'Hello, World!' on the console and exit.
;  USES
;    cons and sys modules
;******

dgroup	group	data
cgroup	group	code

data	dseg
msg	db	'Hello, World!', 0dh, 0ah, 0

code	cseg
	public	main
	extrn	prstr:near, term:near

main:
	mov	ax, offset msg
	push	ax
	call	prstr

	mov	ax, 0
	push	ax
	call	term

	ret

end
