public exit, getdate, setdate, gettime, settime


extrn osterm:near, osexec:near
extrn osgetdate:near, ossetdate:near, osgettime:near, ossettime:near

	cseg
exit:
	push	bp
	mov	bp, sp

	mov	ax, 4[bp]
	push	ax
	call	osterm

	pop	bp
	ret	2


getdate:
	push	bp
	mov	bp, sp

	mov	ax, 8[bp]
	push	ax
	mov	ax, 6[bp]
	push	ax
	mov	ax, 4[bp]
	push	ax
	call	osgetdate

	pop	bp
	ret	6


setdate:
	push	bp
	mov	bp, sp

	mov	ax, 8[bp]
	push	ax
	mov	ax, 6[bp]
	push	ax
	mov	ax, 4[bp]
	push	ax
	call	ossetdate

	pop	bp
	ret	6


gettime:
	push	bp
	mov	bp, sp

	mov	ax, 8[bp]
	push	ax
	mov	ax, 6[bp]
	push	ax
	mov	ax, 4[bp]
	push	ax
	call	osgettime

	pop	bp
	ret	6


settime:
	push	bp
	mov	bp, sp

	mov	ax, 8[bp]
	push	ax
	mov	ax, 6[bp]
	push	ax
	mov	ax, 4[bp]
	push	ax
	call	ossettime

	pop	bp
	ret	6


end
