; read line test

public entry
extrn read_line:near, print_string:near, print_line:near
extrn terminate:near

bufsz		equ	20

		dseg
prompt		db	'Enter a string: ', 0
message		db	'You entered: ', 0
buffer		rb	bufsz

		cseg
entry:
	mov	ax, offset prompt
	push	ax
	call	print_string

	mov	ax, 20
	push	ax
	mov	ax, offset buffer
	push	ax
	call	read_line

	mov	ax, offset message
	push	ax
	call	print_string

	mov	ax, offset buffer
	push	ax
	call	print_line

	mov	al, 0
	call	terminate

end
