; read line test

public entry
extrn print_string:near, print_line:near, new_line:near
extrn print_integer:near
extrn read_line:near
extrn terminate:near

bufsz		equ	20

		dseg
prompt		db	'Enter a string: ', 0
message		db	'You entered: ', 0
msg_len		db	'The length is: ', 0
buffer		rb	bufsz
len		rw	1

		cseg
entry:
	mov	ax, offset prompt
	push	ax
	call	print_string

	mov	ax, 20
	push	ax
	mov	ax, offset buffer
	push	ax
	call	read_line
	mov	len, ax

	mov	ax, offset message
	push	ax
	call	print_string

	mov	ax, offset buffer
	push	ax
	call	print_line

	mov	ax, offset msg_len
	push	ax
	call	print_string

	push	len
	call	print_integer
	call	new_line

	mov	al, 0
	call	terminate

end
